'save_dir': './../generated_data_v1'
'DIR': 'us_import1'
'train_data_file': 'train_data.csv'
'test_data_file': 'test_data.csv'
'id_col': 'PanjivaRecordID'
'num_jobs': 40
'hscode_col': 'HSCode'
'us_import1':
  'use_cols':
    - PanjivaRecordID
    - ConsigneePanjivaID
    - ShipperPanjivaID
    - Carrier
    - ShipmentOrigin
    - ShipmentDestination
    - PortOfUnlading
    - PortOfLading
    - HSCode
    - VolumeTEU
    - Quantity
    - WeightKg
    - ValueOfGoodsUSD
  'numeric_columns':
    - VolumeTEU
    - WeightKg
    - ValueOfGoodsUSD
  'num_neg_samples': 10
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'low_freq_bound': 10

'us_import2':
  'use_cols':
    - PanjivaRecordID
    - ConsigneePanjivaID
    - ShipperPanjivaID
    - Carrier
    - ShipmentOrigin
    - ShipmentDestination
    - PortOfUnlading
    - PortOfLading
    - HSCode
    - VolumeTEU
    - Quantity
    - WeightKg
    - ValueOfGoodsUSD
  'numeric_columns':
    - VolumeTEU
    - WeightKg
    - ValueOfGoodsUSD
  'num_neg_samples': 10
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'low_freq_bound': 10
  
'us_import3':
  'use_cols':
    - PanjivaRecordID
    - ConsigneePanjivaID
    - ShipperPanjivaID
    - Carrier
    - ShipmentOrigin
    - ShipmentDestination
    - PortOfUnlading
    - PortOfLading
    - HSCode
    - VolumeTEU
    - Quantity
    - WeightKg
    - ValueOfGoodsUSD
  'numeric_columns':
    - VolumeTEU
    - WeightKg
    - ValueOfGoodsUSD
  'num_neg_samples': 10
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'low_freq_bound': 10
